import { IEntity } from './types';
import { faker } from '@faker-js/faker';

export const products: IEntity.Product[] = [
	{
		id: faker.string.uuid(),
		name: 'Tandir Lavash',
		category: 'Lavashlar',
		size: 'Kichik',
		price: `${faker.commerce.price({ max: 10 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/5f2359b1-de44-417e-9eaa-f3c4ce022a70.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Sirniy Lavash',
		category: 'Lavashlar',
		size: 'Katta',
		price: `${faker.commerce.price({ max: 10 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/19958d56-324e-4160-a2a0-332ac5909643.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Oddiy Lavash',
		category: 'Lavashlar',
		size: 'O`rtacha',
		price: `${faker.commerce.price({ max: 10 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/19958d56-324e-4160-a2a0-332ac5909643.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Burger',
		category: 'Burgerlar',
		size: 'Kichik',
		price: `${faker.commerce.price({ max: 10 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/ebf8f94e-af46-4bc1-b065-189b58bf0180.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Chizbuger',
		category: 'Burgerlar',
		size: 'O`rtacha',
		price: `${faker.commerce.price({ max: 10 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/46c6f5d0-7542-4d10-bacd-3f65ee788b27.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Big Burger',
		category: 'Burgerlar',
		size: 'Katta',
		price: `${faker.commerce.price({ max: 10 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/c8299ff7-649c-4328-9555-d6f268efe5af.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Peperonniy',
		category: 'Pitsalar',
		size: 'Kichik',
		price: `${faker.commerce.price({ max: 10, min: 5 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/97c621b2-76a6-4e50-bc2a-e423127e490f.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Donar',
		category: 'Pitsalar',
		size: 'O`rtacha',
		price: `${faker.commerce.price({ max: 10, min: 5 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/477fe413-94cc-4e5d-bbfe-4075604bb8d5.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Kombo',
		category: 'Pitsalar',
		size: 'Katta',
		price: `${faker.commerce.price({ max: 10, min: 5 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/ccacb948-8d58-47ee-9e4d-0e63612a227c.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Pepsi',
		category: 'Ichimliklar',
		size: '0.4l',
		price: `${faker.commerce.price({ max: 5 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/60f3568b-6958-4ec0-bf51-b92334b7dfa9.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Mirinda',
		category: 'Ichimliklar',
		size: '0.4l',
		price: `${faker.commerce.price({ max: 5 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/4555485c-c41f-47e0-a14d-12270d8ca5f1.jpg',
	},
	{
		id: faker.string.uuid(),
		name: 'Mounten',
		category: 'Ichimliklar',
		size: '0.4l',
		price: `${faker.commerce.price({ max: 5 })}$`,
		img: 'http://cc.oqtepalavash.uz/api/image/94a6bae1-6a9c-494d-8418-6d9117cc1bc3.jpg',
	},
];
